# syntax - https://github.com/redhat-plumbers-in-action/advanced-issue-labeler#policy
---

policy:
  - template: ['bug.yml', 'feature.yml']
    section:
      - id: ['type']
        block-list: ['other']
        label:
          - name: bug 🐛
            keys: ['Bug Report']

          - name: RFE 🎁
            keys: ['Feature Request']
